# Generated by Django 4.2.23 on 2025-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст цитаты. Должен быть уникальным, без повторов.', unique=True)),
                ('source', models.CharField(help_text='Источник цитаты (например, название фильма или книги).', max_length=200)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Вес цитаты для вероятностной выдачи (чем больше — тем выше шанс).')),
                ('likes', models.IntegerField(default=0, help_text='Количество лайков.')),
                ('dislikes', models.IntegerField(default=0, help_text='Количество дизлайков.')),
                ('views', models.IntegerField(default=0, help_text='Счётчик количества просмотров.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания цитаты.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Дата и время последнего обновления цитаты.')),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
            },
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('text',), name='unique_quote_text'),
        ),
    ]
