# Generated by Django 4.2.23 on 2025-08-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quotereaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='likes',
        ),
    ]
